---
# 파일 배포
# (ansible) custom.fact -- 배포 -->  (web1) /etc/asnbile/facts.d/custom.fact
- name: 사용자 정의 팩트 파일 배포
  hosts: webserver
  gather_facts: no
  tasks:
  - name: 폴더 만들기
    file: 
      path: /etc/ansible/facts.d
      state: directory
  - name: 파일 전송
    copy:
      src: custom.fact
      dest: /etc/ansible/facts.d/custom.fact
      