---
- name: 하드웨어정보 수집하기
  hosts: all
  gather_facts: yes
  tasks:
  - name: results 디렉토리 삭제
    ansible.builtin.file:
      path: results
      state: absent

  # 1. 템플릿 파일 배포(/root/hwreport.txt)
  - name: 1. 템플릿 파일 배포(/root/hwreport.txt)
    copy:
      src: files/hwreport.txt
      dest: /root/hwreport.txt
      owner: root
      group: root
      mode: '0400'
  # 2. 하드웨어 정보 수집
  # 인벤토리 호스트 이름
  - name: 인벤토리 호스트 이름 수집
    replace:
      path: /root/hwreport.txt
      regexp: 'inventoryhostname$'
      replace: '{{ ansible_hostname }}'
  # 총 메모리
  - name: 총 메모리 수집
    replace:
      path: /root/hwreport.txt
      regexp: 'totalmem$'
      replace: "{{ ansible_memtotal_mb }}"
  # 바이오스 버전
  - name: 바이오스 버전
    replace:
      path: /root/hwreport.txt
      regexp: 'biosversion$'
      replace: "{{ ansible_bios_version }}"
  # /dev/sda/ 디스크 크기
  - name: /dev/sda 디스크 크기
    replace:
      path: /root/hwreport.txt
      regexp: 'sdasize$'
      replace: "{{ ansible_devices.sda.size }}"
  # /dev/sda/ 디스크 크기
  # 3. 하드웨어 정보 파일 수집
  - name: /root/hwreport.txt 파일 수집
    fetch:
      src: /root/hwreport.txt
      # dest를 result로 지정했을 때 vs flat하게 파일 이름 지정하기
      dest: results/hwreport-{{ inventory_hostname }}.txt
      flat: yes
