---
- name: Time Synchronization
  hosts: datacenters

  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name: Set timezone
      timezone:
        name: "{{ host_timezone }}"
      notify: restart_chronyd

  handlers:
    - name: restart_chronyd
      service:
        name: chronyd
        state: restarted
        