---
- name: Use myvhost role playbook
  hosts: webservers
  pre_tasks:
    - name: pre_tasks message
      debug:
        msg: 'Ensure web server configuration.'

  roles:
    - myvhost

  post_tasks:
    - name: HTML content is installed
      copy:
        src: index.html.j2
        dest: "/var/www/vhosts/{{ ansible_hostname }}"

    - name: post_tasks message
      debug:
        msg: 'web server is configured.'
