---
- name: 환경 파일 배포
  gather_facts: no
  hosts: all
  remote_user: devops
  become: false
  tasks:
    - name: 환경 파일 배포 - $HOME/.bashrc
      template: 
        src: templates/ps1.j2
        dest: /home/devops/.bashrc
        owner: devops
        group: devops
        mode: '0644'
    - name: 디렉토리 복사
      copy:
        src: files/blesh
        dest: .local/share
        