---
# play 1 - ansible1
#1. package installation - http, mod_ssl, firewalld
# 2. web service configuration - /var/www/html/index.html
# 3. service enable - httpd, firewalld
# 4. firewall enroll - http, https
# play 2 - localhost(ansibleA)
# check web request - curl http://web1.example.com

- name: Play (1) - configure web setting
  hosts: web1.example.com
  tasks:
    - name: Package installation
      yum:
        name: 
          - httpd
          - mod_ssl
          - firewalld
        state: latest
    - name: WEB configuration - /var/www/html/index.html
      copy:
        content: |
          <html>
          <h1><center>web1.example.com</center></h1>
          </html>
        dest: /var/www/html/index.html
    - name: WEB enable - httpd, firewalld
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld
    - name: Firewall enroll
      firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - 80/tcp
        - 443/tcp

- name: Play (2) - localhost
  hosts: localhost
  become: false
  tasks:
    - name: check web - curl
      uri:
        url: http://web1
        return_content: true
        status_code: 200
