---
- name: 웹서비스 되돌리기
  hosts: all
  vars_files:
    - vars/web.yml
  tasks:
  - name: 방화벽 서비스 포트 내리기
    firewalld:
      service: "{{ item }}"
      permanent: yes
      immediate: yes
      state: disabled
    loop:
    - "{{ fw_http }}"
    - "{{ fw_https }}"
  - name: 웹 서비스 내리기
    service:
      name: "{{ svc_web }}"
      enabled: no
      state: stopped
  - name: 웹 서비스 파일 삭제
    file:
      path: /var/www/html/index.html
      state: absent
  - name: 웹 서비스 삭제
    yum:
      name: 
        - "{{ pkg_web_http }}"
        - "{{ pkg_web_https }}"
      state: absent
      