- name: DB 패키지 설치
  hosts: database_prod
  tasks:
  - name: 패키지 설치
    # yum:
    #   name: "{{item}}"
    #   state: latest
    # loop: "{{ pkg_db }}"
    # vars:
    #   pkg_db:
    #   - mariadb-server
    #   - python3-PyMySQL 
    # =>> yum을 두번 실행한것과 같다.

    yum:
      name: "{{ pkg_db }}"
      state: latest
    vars:
      pkg_db:
      - mariadb-server
      - python3-PyMySQL
    # when: ansible_distribution == "CentOS"
    when: ansible_distribution == 'debian'
  # =>> yum을 한 번 돌린 것과 같다. 

  - name: 서비스 기동
    service:
      name: mariadb
      state: started
      enabled: yes
